name: Windows-CRD

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Initializing Setup
      shell: pwsh
      run: ./setup.ps1

    - name: Starting CRD 
      shell: pwsh
      run: |
        $authcode = "${{ github.event.inputs.authcode }}"
        $pincode = "${{ github.event.inputs.pincode }}"
        # Assuming you have a script to start CRD which uses authcode and pincode
        # Replace `Start-CRD.ps1` with the actual script that starts Chrome Remote Desktop
        ./Start-CRD.ps1 -authcode $authcode -pin $pincode

    - name: Keep Alive
      shell: pwsh
      run: ./timeout.ps1
